name: Auto Deploy Trigger

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  empty_commit:
    runs-on: ubuntu-latest
    if: github.actor != 'James Hou'
    steps:
      - name: Push to vercel
        uses: actions/checkout@v3

      - name: Push to vercel
        run: |
          git config user.email "james.william.hou@gmail.com"
          git config user.name "James Hou"
          git commit --allow-empty -m "Push to vercel"
          git push